FROM python:3.10
RUN pip install --no-cache-dir \
    torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu/torch_stable.html && \
    pip install --no-cache-dir transformers

