FROM python:3.10
RUN pip install --no-cache-dir \
    torch==2.1.0+cpu  torchvision torchaudio --index-url --index-url https://download.pytorch.org/whl/cpu && \
    pip install --no-cache-dir transformers

